apiVersion: apps/v1
kind: Pod
metadata:
  name: knote
  labels:
    name: knote
spec:
  containers:
        - name: knote
          image: 361435822559.dkr.ecr.us-east-1.amazonaws.com/my_apps:knoteapp
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Always
